// Code generated by goctl. DO NOT EDIT!
// Source: nft.proto

package nft

import (
	"context"

	"togetherdao/nft/rpc/project"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ProjectReq  = project.ProjectReq
	ProjectResp = project.ProjectResp

	Nft interface {
		Add(ctx context.Context, in *ProjectReq, opts ...grpc.CallOption) (*ProjectResp, error)
	}

	defaultNft struct {
		cli zrpc.Client
	}
)

func NewNft(cli zrpc.Client) Nft {
	return &defaultNft{
		cli: cli,
	}
}

func (m *defaultNft) Add(ctx context.Context, in *ProjectReq, opts ...grpc.CallOption) (*ProjectResp, error) {
	client := project.NewNftClient(m.cli.Conn())
	return client.Add(ctx, in, opts...)
}
