// Code generated by goctl. DO NOT EDIT!
// Source: nft.proto

package server

import (
	"context"

	"togetherdao/nft/rpc/internal/logic"
	"togetherdao/nft/rpc/internal/svc"
	"togetherdao/nft/rpc/project"
)

type NftServer struct {
	svcCtx *svc.ServiceContext
	project.UnimplementedNftServer
}

func NewNftServer(svcCtx *svc.ServiceContext) *NftServer {
	return &NftServer{
		svcCtx: svcCtx,
	}
}

func (s *NftServer) Add(ctx context.Context, in *project.ProjectReq) (*project.ProjectResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
